### ISSUE TITLE
Logic for state changes for recognized and unrecognized assays

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#263]
This gathers some JIRA-VOYAGER enhancements as requested by @timosong and @webbera

- [x] Handle FASTQs Not Available #264 
- [x] Create a list of recognized assays/bait sets to assist state changes in JIRA (1.5.0) #265
- [x] Resolve unrecognized assays (1.5.0) #266
