### ISSUE TITLE
Import DMP bams

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#66]
DMP bams need to be imported into beagle DB as a different set of normals to be used in lieu of a matching patient normal from a request or historical patient data.

- [x] Interact with CRDB to get access to their data
- [x] Implement endpoint interim solution
- [x] Export three request IDs for test #194 
- [x] Restrict access to Voyager to CMO-only users #195
- [x] Add dmp bam pairing #233

**Comment by allanbolipata** [comment]
I'll investigate to find endpoints to accomplish this instead of existing method

**Comment by allanbolipata** [comment]
@ckandoth will be asking the product owners if they can provide an endpoint

**Comment by ckandoth** [comment]
The contact is Kai-Hsiung Lin in Research and Technology Management. I have followed-up on the old thread from July 2019 where I asked for an endpoint that could map CMO to DMP patient IDs. Everyone in CI is CC'ed.

**Comment by ckandoth** [comment]
@sivkovic @allanbolipata Notes on current implementation of DMP BAM importing and sample naming in LIMS is documented in several confluence pages. [Start here](http://plvpipetrack1.mskcc.org:8099/display/IDT/DMP+Samples+to+IGO+Samples).

**Comment by allanbolipata** [comment]
@soccin Will update progress on this with checklist

**Comment by soccin** [comment]
Test of reply to @ message

**Comment by allanbolipata** [comment]
Complete!
